name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          # Darwin ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o sniffy-darwin-arm64

          # Darwin AMD64 (Intel Mac)
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o sniffy-darwin-amd64

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o sniffy-linux-arm64

          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o sniffy-linux-amd64

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Create release with GitHub CLI
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "Release $VERSION of Sniffy Scan" \
            --latest \
            sniffy-darwin-arm64 \
            sniffy-darwin-amd64 \
            sniffy-linux-arm64 \
            sniffy-linux-amd64
